# 【問題1】行列積を手計算する

$$
A=
\begin{pmatrix}
-1&2&3\\
4&-5&6\\
7&8&-9
\end{pmatrix}\quad
B=
\begin{pmatrix}
0&2&1\\
0&2&-8\\
2&9&-1
\end{pmatrix}
$$

$$
AB =
\begin{pmatrix}
-1&2&3\\
4&-5&6\\
7&8&-9
\end{pmatrix}
\begin{pmatrix}
0&2&1\\
0&2&-8\\
2&9&-1
\end{pmatrix}
$$

$$
=
\begin{pmatrix}
(-1\times0) + (2\times0) + (3\times2)&(-1\times2) + (2\times2) + (3\times9)&(-1\times1) + (2\times-8) + (3\times-1)\\
(4\times0) + (-5\times0) + (6\times2)&(4\times2) + (-5\times2) + (6\times9)&(4\times1) + (-5\times-8) + (6\times-1)\\
(7\times0) + (8\times0) + (-9\times2)&(7\times2) + (8\times2) + (-9\times9)&(7\times1) + (8\times-8) + (-9\times-1)
\end{pmatrix}
$$

$$
=
\begin{pmatrix}
6&29&-20\\
12&52&38\\
-18&-51&-48
\end{pmatrix}
$$

# 【問題2】NumPyの関数による計算

In [2]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 行列の積
ab_ndarray = np.matmul(a_ndarray, b_ndarray)
print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題3】ある要素の計算を実装

In [40]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

rows = 3 # a_ndarrayの行数
columns = 3 # b_ndarrayの列数
list_ab = []

for row in range(rows):
    list_buf = []
    ndarray_row = a_ndarray[row,:] # a_ndarrayの現在の行のndarrayを取得
    for column in range(columns):
        ndarray_column = b_ndarray[:,column] # b_ndarray現在の列のndarrayを取得
        list_buf.append(np.sum(ndarray_row*ndarray_column))
    list_ab.append(list_buf)
    
ab_ndarray = np.array(list_ab)
print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題4】行列積を行う関数の作成

In [84]:
def MatrixProduct(a_ndarray, b_ndarray):
    rows = a_ndarray.shape[0] # a_ndarrayの列数
    columns = b_ndarray.shape[1] # b_ndarrayの行数
    list_ab = []

    for row in range(rows):
        list_buf = []
        ndarray_row = a_ndarray[row,:] # a_ndarrayの現在の行のndarrayを取得
        for column in range(columns):
            ndarray_column = b_ndarray[:,column] # b_ndarrayの現在の列のndarrayを取得
            list_buf.append(np.sum(ndarray_row*ndarray_column))
        list_ab.append(list_buf)

    ab_ndarray = np.array(list_ab)
    return ab_ndarray

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ab_ndarray = MatrixProduct(a_ndarray, b_ndarray)
print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題5】計算が定義されない入力を判定する

In [79]:
import sys

def MatrixProductWithValidation(a_ndarray, b_ndarray):
    rows = a_ndarray.shape[0] # a_ndarrayの列数
    columns = b_ndarray.shape[1] # b_ndarrayの行数
    list_ab = []
    
    #  Aの列数とBの行数が等しくない場合
    if a_ndarray.shape[1]!=b_ndarray.shape[0]:
        print("[ERROR]: Aの列数とBの行数が等しくありません。")
        return

    for row in range(rows):
        list_buf = []
        ndarray_row = a_ndarray[row,:] # a_ndarrayの現在の行のndarrayを取得
        for column in range(columns):
            ndarray_column = b_ndarray[:,column] # b_ndarrayの現在の列のndarrayを取得
            list_buf.append(np.sum(ndarray_row*ndarray_column))
        list_ab.append(list_buf)

    ab_ndarray = np.array(list_ab)
    return ab_ndarray

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8]])
ab_ndarray = MatrixProductWithValidation(a_ndarray, b_ndarray)
print(ab_ndarray)

[ERROR]: Aの列数とBの行数が等しくありません。
None


# 【問題6】転置

In [83]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8]])

# Aの列数とBの行数が等しくないため，行列積を計算できない
ab_ndarray = MatrixProductWithValidation(a_ndarray, b_ndarray)
print(ab_ndarray)

# AとB(転置)の行列積
b_ndarray_t = b_ndarray.T
print("Bを転置：\n{}".format(b_ndarray_t))

# ab_ndarray = np.matmul(a_ndarray, b_ndarray_t) # 確認用
ab_ndarray = MatrixProductWithValidation(a_ndarray, b_ndarray_t)
print("AとB(転置)の行列積：\n{}".format(ab_ndarray))

[ERROR]: Aの列数とBの行数が等しくありません。
None
Bを転置：
[[ 0  0]
 [ 2  2]
 [ 1 -8]]
AとB(転置)の行列積：
[[  7 -20]
 [ -4 -58]
 [  7  88]]
