# 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。  
この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。  
Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

## Pandas
・DataFrame  
・Series  
  
## matplotlib
・matplotlib.pyplot.Figure  
  
## scikit-learn
・dummy.DummyClassifier

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。  
最低でもそれぞれ5つ以上答えてください。

## メソッド
・numpy.array  
・numpy.insert  
・matplotlib.pyplot.plot  
・matplotlib.pyplot.show  
・pandas.concat  
  
## インスタンス変数
・numpy.dtype  
・numpy.size  
・numpy.T  
・pandas.DataFrame.index  
・pandas.DataFrame.columns

# 【問題3】標準化クラスをスクラッチで作成

In [1]:
import numpy as np

class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)

        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_)/np.sqrt(self.var_)
        
        return X_scaled

In [2]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# 【問題4】 四則演算を行うクラスの作成

In [3]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
        
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
        
    def sub(self, value2):
        """
        self.valueから受け取った引数を引く
        """
        self.value -= value2        
        
    def mul(self, value2):
        """
        self.valueに受け取った引数をかける
        """
        self.value *= value2
        
    def div(self, value2):
        """
        self.valueに受け取った引数を割る
        """
        self.value /= value2        

In [4]:
example = ExampleClass(5)
print("value : {}".format(example.value))

example.add(3)
print("value : {}".format(example.value))

example.sub(3)
print("value : {}".format(example.value))

example.mul(3)
print("value : {}".format(example.value))

example.div(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8
value : 5
value : 15
value : 5.0
